baseline:
  parent_config: ''
  save:
    init: true
    image: true
    video: true
    video_frame_freq: 1
  trainable:
    point: true
    color: true
    bg: true
    stroke_width: false
    stroke_color: false
  lr_base:
    point: 1
    color: 0.02
    bg: 0.005
    stroke_width: 0.3
    stroke_color: 0.02
  lr:
    lr_init: 0.002
    lr_final: 0.0008
    lr_delay_mult: 0.1
    lr_delay_steps: 100
  num_iter: 1000
  render_size: 600
  cut_size: 512
  xing_loss_weight: 0
  level_of_cc: 0 # 0 - original number of cc / 1 - recommended / 2 - more control points
  seed: 0
  diffusion:
    model: "runwayml/stable-diffusion-v1-5"
    timesteps: 1000
    guidance_scale: 100
  loss:
    use_sds_loss: true
    tone:
      use_tone_loss: false
    conformal:
      use_conformal_loss: false
from_scratch:
  parent_config: baseline
  num_iter: 2000
fine_tune:
  parent_config: baseline
  xing_loss_weight: 1
  num_iter: 250
  loss:
    use_sds_loss: False
conformal_0.5_dist_pixel_100_kernel201:
  parent_config: baseline
  level_of_cc: 1
  loss:
    tone:
      use_tone_loss: true
      dist_loss_weight: 100
      pixel_dist_kernel_blur: 201
      pixel_dist_sigma: 30
    conformal:
      use_conformal_loss: true
      angeles_w: 0.5


